//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ItemGioHang
    {
        public int ID { get; set; }
        public Nullable<int> MaSP { get; set; }
        public string TenSP { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> ThanhTien { get; set; }
        public Nullable<int> MaKH { get; set; }
        public ItemGioHang()
        {

        }
        public ItemGioHang(int maSP)
        {
            using (SellPhoneContext db = new SellPhoneContext())
            {
                SanPham sp = db.SanPhams.Single(n => n.MaSP == maSP);
                this.MaSP = maSP;
                this.TenSP = sp.TenSP;
                this.HinhAnh = sp.HinhAnh;
                this.soluong = 1;
                this.DonGia = (int?)sp.DonGia.Value;
                this.ThanhTien = DonGia * soluong;

            }
        }
    }
}
